/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.AccountInfo;
import model.Fullreport;



public class AccountInfoPanel extends javax.swing.JPanel {

    
    AccountInfo savings;
    AccountInfo checkin;
    Fullreport fullreport;
    public AccountInfoPanel(AccountInfo savings, AccountInfo checkin, Fullreport fullreport) {
        initComponents();
        this.savings=savings;
        this.checkin=checkin;
        this.fullreport=fullreport;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtaccounttype = new javax.swing.JTextField();
        bankheading = new javax.swing.JLabel();
        bankname = new javax.swing.JLabel();
        routingnumber = new javax.swing.JLabel();
        accountnumber = new javax.swing.JLabel();
        accountbalance = new javax.swing.JLabel();
        accounttype = new javax.swing.JLabel();
        txtbankname = new javax.swing.JTextField();
        txtroutingnumber = new javax.swing.JTextField();
        txtaccountnumber = new javax.swing.JTextField();
        txtaccountbalance = new javax.swing.JTextField();
        txtaccounttype1 = new javax.swing.JTextField();
        bankheading1 = new javax.swing.JLabel();
        bankname1 = new javax.swing.JLabel();
        routingnumber1 = new javax.swing.JLabel();
        accountnumber1 = new javax.swing.JLabel();
        accountbalance1 = new javax.swing.JLabel();
        accounttype1 = new javax.swing.JLabel();
        txtbankname1 = new javax.swing.JTextField();
        txtroutingnumber1 = new javax.swing.JTextField();
        txtaccountnumber1 = new javax.swing.JTextField();
        txtaccountbalance1 = new javax.swing.JTextField();
        AccountInfosave = new javax.swing.JButton();

        txtaccounttype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaccounttypeActionPerformed(evt);
            }
        });

        bankheading.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bankheading.setForeground(new java.awt.Color(0, 51, 153));
        bankheading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bankheading.setText("Saving Bank Details");

        bankname.setForeground(new java.awt.Color(0, 51, 153));
        bankname.setText("Bank Name:");

        routingnumber.setForeground(new java.awt.Color(0, 51, 153));
        routingnumber.setText("Routing Number:");

        accountnumber.setForeground(new java.awt.Color(0, 51, 153));
        accountnumber.setText("Account Number:");

        accountbalance.setForeground(new java.awt.Color(0, 51, 153));
        accountbalance.setText("Account Balance:");

        accounttype.setForeground(new java.awt.Color(0, 51, 153));
        accounttype.setText("Account Type:");

        txtaccounttype1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaccounttype1ActionPerformed(evt);
            }
        });

        bankheading1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bankheading1.setForeground(new java.awt.Color(0, 51, 153));
        bankheading1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bankheading1.setText("Checkin Bank Details");

        bankname1.setForeground(new java.awt.Color(0, 51, 153));
        bankname1.setText("Bank Name:");

        routingnumber1.setForeground(new java.awt.Color(0, 51, 153));
        routingnumber1.setText("Routing Number:");

        accountnumber1.setForeground(new java.awt.Color(0, 51, 153));
        accountnumber1.setText("Account Number");

        accountbalance1.setForeground(new java.awt.Color(0, 51, 153));
        accountbalance1.setText("Account Balance:");

        accounttype1.setForeground(new java.awt.Color(0, 51, 153));
        accounttype1.setText("Account Type:");

        txtbankname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbankname1ActionPerformed(evt);
            }
        });

        txtroutingnumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtroutingnumber1ActionPerformed(evt);
            }
        });

        txtaccountnumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaccountnumber1ActionPerformed(evt);
            }
        });

        AccountInfosave.setForeground(new java.awt.Color(0, 51, 153));
        AccountInfosave.setText("Save");
        AccountInfosave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountInfosaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bankheading, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bankheading1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(accounttype1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(81, 81, 81)
                                    .addComponent(txtaccounttype1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(accountnumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtaccountnumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(accountbalance, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                                .addComponent(accountnumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(routingnumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(bankname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(accounttype, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bankname1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(routingnumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(70, 70, 70)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtroutingnumber, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                                .addComponent(txtaccountnumber)
                                                .addComponent(txtaccountbalance)
                                                .addComponent(txtbankname)
                                                .addComponent(txtaccounttype))
                                            .addComponent(txtbankname1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtroutingnumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(accountbalance1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtaccountbalance1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(AccountInfosave)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bankheading, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtbankname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtroutingnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bankname, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(routingnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accountnumber)
                    .addComponent(txtaccountnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtaccountbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtaccounttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accounttype, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bankheading1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bankname1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbankname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(routingnumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtroutingnumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accountnumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtaccountnumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accountbalance1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtaccountbalance1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accounttype1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtaccounttype1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AccountInfosave)
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtaccounttypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaccounttypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaccounttypeActionPerformed

    private void txtaccounttype1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaccounttype1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaccounttype1ActionPerformed

    private void txtbankname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbankname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbankname1ActionPerformed

    private void txtroutingnumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtroutingnumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtroutingnumber1ActionPerformed

    private void txtaccountnumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaccountnumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaccountnumber1ActionPerformed

    private void AccountInfosaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountInfosaveActionPerformed
        savings.setBankname(txtbankname.getText());
        savings.setRoutingnumber(txtroutingnumber.getText());
        savings.setAccountnumber(txtaccountnumber.getText());
        savings.setAccountbalance(txtaccountbalance.getText());
        savings.setAccounttype(txtaccounttype.getText());
        checkin.setBankname(txtbankname1.getText());
        checkin.setRoutingnumber(txtroutingnumber1.getText());
        checkin.setAccountnumber(txtaccountnumber1.getText());
        checkin.setAccountbalance(txtaccountbalance1.getText());
        checkin.setAccounttype(txtaccounttype1.getText());
        
        fullreport.setSavings(savings);
        fullreport.setCheckin(checkin);
       JOptionPane.showMessageDialog(this,"Bank Details Entered");
    }//GEN-LAST:event_AccountInfosaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccountInfosave;
    private javax.swing.JLabel accountbalance;
    private javax.swing.JLabel accountbalance1;
    private javax.swing.JLabel accountnumber;
    private javax.swing.JLabel accountnumber1;
    private javax.swing.JLabel accounttype;
    private javax.swing.JLabel accounttype1;
    private javax.swing.JLabel bankheading;
    private javax.swing.JLabel bankheading1;
    private javax.swing.JLabel bankname;
    private javax.swing.JLabel bankname1;
    private javax.swing.JLabel routingnumber;
    private javax.swing.JLabel routingnumber1;
    private javax.swing.JTextField txtaccountbalance;
    private javax.swing.JTextField txtaccountbalance1;
    private javax.swing.JTextField txtaccountnumber;
    private javax.swing.JTextField txtaccountnumber1;
    private javax.swing.JTextField txtaccounttype;
    private javax.swing.JTextField txtaccounttype1;
    private javax.swing.JTextField txtbankname;
    private javax.swing.JTextField txtbankname1;
    private javax.swing.JTextField txtroutingnumber;
    private javax.swing.JTextField txtroutingnumber1;
    // End of variables declaration//GEN-END:variables
}
