/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.Fullreport;
import model.Product;

public class DemoPanel extends javax.swing.JPanel {

    Product product;
    Fullreport fullreport;
    
    public DemoPanel(Product product,Fullreport fullreport) {
        initComponents();
        this.product= product;
        this.fullreport=fullreport;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtphonenumber = new javax.swing.JTextField();
        lastname = new javax.swing.JLabel();
        txtdateofbirth = new javax.swing.JTextField();
        phonenumber = new javax.swing.JLabel();
        dateofbirth = new javax.swing.JLabel();
        addressheading = new javax.swing.JLabel();
        firstname = new javax.swing.JLabel();
        txtlastname = new javax.swing.JTextField();
        age = new javax.swing.JLabel();
        weight = new javax.swing.JLabel();
        height = new javax.swing.JLabel();
        ssn = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        txtweight = new javax.swing.JTextField();
        txtheight = new javax.swing.JTextField();
        txtssn = new javax.swing.JTextField();
        demosavebtn = new javax.swing.JButton();
        txtfirstname = new javax.swing.JTextField();

        lastname.setForeground(new java.awt.Color(0, 51, 153));
        lastname.setText("Last Name:");

        phonenumber.setForeground(new java.awt.Color(0, 51, 153));
        phonenumber.setText("Phone Number:");

        dateofbirth.setForeground(new java.awt.Color(0, 51, 153));
        dateofbirth.setText("Date of Birth:");

        addressheading.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addressheading.setForeground(new java.awt.Color(0, 51, 153));
        addressheading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addressheading.setText("Demographic Information");
        addressheading.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        firstname.setForeground(new java.awt.Color(0, 51, 153));
        firstname.setText("First Name:");

        txtlastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlastnameActionPerformed(evt);
            }
        });

        age.setForeground(new java.awt.Color(0, 51, 153));
        age.setText("Age:");

        weight.setForeground(new java.awt.Color(0, 51, 153));
        weight.setText("Weight:");

        height.setForeground(new java.awt.Color(0, 51, 153));
        height.setText("Height:");

        ssn.setForeground(new java.awt.Color(0, 51, 153));
        ssn.setText("Social Security Number:");

        demosavebtn.setForeground(new java.awt.Color(0, 51, 153));
        demosavebtn.setText("Save");
        demosavebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demosavebtnActionPerformed(evt);
            }
        });

        txtfirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfirstnameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ssn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(112, 112, 112)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtphonenumber, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(txtdateofbirth)
                            .addComponent(txtage)
                            .addComponent(txtweight)
                            .addComponent(txtheight)
                            .addComponent(txtssn)
                            .addComponent(txtlastname)
                            .addComponent(txtfirstname)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(addressheading, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(demosavebtn)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addressheading, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtphonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonenumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateofbirth)
                    .addComponent(txtdateofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(age)
                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weight)
                    .addComponent(txtweight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtheight, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssn)
                    .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(demosavebtn)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtlastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastnameActionPerformed

    private void demosavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demosavebtnActionPerformed
       product.setFirstname(txtfirstname.getText());
       product.setLastname(txtlastname.getText());
       product.setPhonenumber(txtphonenumber.getText());
       product.setDateofbirth(txtdateofbirth.getText());
       product.setAge(txtage.getText());
       product.setWeight(txtweight.getText());
       product.setHeight(txtheight.getText());
       product.setSsn(txtssn.getText());
       
       fullreport.setProduct(product);
       JOptionPane.showMessageDialog(this,"Personal Details Entered");
       
        
    }//GEN-LAST:event_demosavebtnActionPerformed

    private void txtfirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstnameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressheading;
    private javax.swing.JLabel age;
    private javax.swing.JLabel dateofbirth;
    private javax.swing.JButton demosavebtn;
    private javax.swing.JLabel firstname;
    private javax.swing.JLabel height;
    private javax.swing.JLabel lastname;
    private javax.swing.JLabel phonenumber;
    private javax.swing.JLabel ssn;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtdateofbirth;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtheight;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtphonenumber;
    private javax.swing.JTextField txtssn;
    private javax.swing.JTextField txtweight;
    private javax.swing.JLabel weight;
    // End of variables declaration//GEN-END:variables
}
