/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.lang.System.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Driver;
import model.Fullreport;

/**
 *
 * @author Deepika Reddy
 */
public class DriverPanel extends javax.swing.JPanel {

    Driver driver;
    Fullreport fullreport;
    public DriverPanel(Driver driver, Fullreport fullreport) {
        initComponents();
        this.driver=driver;
        this.fullreport=fullreport;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        driverheading = new javax.swing.JLabel();
        licensenumber = new javax.swing.JLabel();
        dateofissue = new javax.swing.JLabel();
        dateofexpiration = new javax.swing.JLabel();
        bloodtype = new javax.swing.JLabel();
        picture = new javax.swing.JLabel();
        txtlicense = new javax.swing.JTextField();
        txtdateofissue = new javax.swing.JTextField();
        txtdateofexpiration = new javax.swing.JTextField();
        txtbloodtype = new javax.swing.JTextField();
        driversave = new javax.swing.JButton();
        picturelabel = new javax.swing.JLabel();
        upload = new javax.swing.JButton();

        driverheading.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        driverheading.setForeground(new java.awt.Color(0, 51, 153));
        driverheading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        driverheading.setText("Driver License Details");

        licensenumber.setForeground(new java.awt.Color(0, 51, 153));
        licensenumber.setText("License Number:");

        dateofissue.setForeground(new java.awt.Color(0, 51, 153));
        dateofissue.setText("Date of Issue:");

        dateofexpiration.setForeground(new java.awt.Color(0, 51, 153));
        dateofexpiration.setText("Date of Expiration:");

        bloodtype.setForeground(new java.awt.Color(0, 51, 153));
        bloodtype.setText("Blood Type:");

        picture.setForeground(new java.awt.Color(0, 51, 153));
        picture.setText("Picture:");

        txtlicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlicenseActionPerformed(evt);
            }
        });

        driversave.setForeground(new java.awt.Color(0, 51, 153));
        driversave.setText("Save");
        driversave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driversaveActionPerformed(evt);
            }
        });

        picturelabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        upload.setForeground(new java.awt.Color(0, 51, 153));
        upload.setText("Upload");
        upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(picture)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(licensenumber)
                                            .addComponent(dateofissue)
                                            .addComponent(dateofexpiration)
                                            .addComponent(bloodtype))
                                        .addGap(75, 75, 75))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(driversave)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(upload)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtlicense)
                                        .addComponent(txtdateofissue)
                                        .addComponent(txtdateofexpiration)
                                        .addComponent(txtbloodtype, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                        .addComponent(picturelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(driverheading, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(driverheading)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(licensenumber)
                    .addComponent(txtlicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateofissue)
                    .addComponent(txtdateofissue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateofexpiration)
                    .addComponent(txtdateofexpiration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodtype)
                    .addComponent(txtbloodtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(picture)
                    .addComponent(picturelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upload)
                    .addComponent(driversave))
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void driversaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driversaveActionPerformed
        driver.setLicense(txtlicense.getText());
        driver.setDateofissue(txtdateofissue.getText());
        driver.setDateofexpiration(txtdateofexpiration.getText());
        driver.setBloodtype(txtbloodtype.getText());
        
        fullreport.setDriver(driver);
       JOptionPane.showMessageDialog(this,"Driver License Details Entered");
        
    }//GEN-LAST:event_driversaveActionPerformed

    private void txtlicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlicenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlicenseActionPerformed

    private void uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadActionPerformed
        JFileChooser fileChooser = new JFileChooser();        
        fileChooser.showOpenDialog(null);
       
        BufferedImage bfImage = null;
        try {
            File fileImage = fileChooser.getSelectedFile();
            bfImage = ImageIO.read(new File(fileImage.getAbsolutePath()));
        } catch (IOException ex) {
        }
        
        Image pic = bfImage.getScaledInstance(picturelabel.getWidth(), picturelabel.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon Imicon = new ImageIcon(pic);
        
                 picturelabel.setIcon(Imicon);
        driver.setPicture(pic);
    }//GEN-LAST:event_uploadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bloodtype;
    private javax.swing.JLabel dateofexpiration;
    private javax.swing.JLabel dateofissue;
    private javax.swing.JLabel driverheading;
    private javax.swing.JButton driversave;
    private javax.swing.JLabel licensenumber;
    private javax.swing.JLabel picture;
    private javax.swing.JLabel picturelabel;
    private javax.swing.JTextField txtbloodtype;
    private javax.swing.JTextField txtdateofexpiration;
    private javax.swing.JTextField txtdateofissue;
    private javax.swing.JTextField txtlicense;
    private javax.swing.JButton upload;
    // End of variables declaration//GEN-END:variables
}
