/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.AccountInfo;
import model.Address;
import model.Driver;
import model.Fullreport;
import model.Medical;
import model.Product;

/**
 *
 * @author Deepika Reddy
 */
public class MainJFrame extends javax.swing.JFrame {

    Product product;
    Address address;
    AccountInfo savings;
    AccountInfo checkin;
    Driver driver;
    Medical medical;
    Fullreport fullreport;
    public MainJFrame() {
        initComponents();
        product= new Product();
        address= new Address();
        driver= new Driver();
        medical = new Medical();
        savings= new AccountInfo();
        checkin= new AccountInfo();
        
        fullreport = new Fullreport();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        ControlPanel = new javax.swing.JPanel();
        Demographic = new javax.swing.JButton();
        Address = new javax.swing.JButton();
        AccountInfo = new javax.swing.JButton();
        DriverLicense = new javax.swing.JButton();
        MedicalRecord = new javax.swing.JButton();
        ViewDemo = new javax.swing.JButton();
        viewaddress = new javax.swing.JButton();
        ViewDriverLicense = new javax.swing.JButton();
        ViewMedicalRecord = new javax.swing.JButton();
        ViewAccountInfo = new javax.swing.JButton();
        ReportDetails = new javax.swing.JButton();
        Workarea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane.setDividerLocation(60);

        ControlPanel.setToolTipText("");

        Demographic.setForeground(new java.awt.Color(0, 51, 153));
        Demographic.setText("Demographic");
        Demographic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemographicActionPerformed(evt);
            }
        });

        Address.setForeground(new java.awt.Color(0, 51, 153));
        Address.setText("Address");
        Address.setMaximumSize(new java.awt.Dimension(123, 23));
        Address.setMinimumSize(new java.awt.Dimension(123, 23));
        Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressActionPerformed(evt);
            }
        });

        AccountInfo.setForeground(new java.awt.Color(0, 51, 153));
        AccountInfo.setText("AccountInfo");
        AccountInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountInfoActionPerformed(evt);
            }
        });

        DriverLicense.setForeground(new java.awt.Color(0, 51, 153));
        DriverLicense.setText("DriverLicense");
        DriverLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DriverLicenseActionPerformed(evt);
            }
        });

        MedicalRecord.setForeground(new java.awt.Color(0, 51, 153));
        MedicalRecord.setText("MedicalRecord");
        MedicalRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicalRecordActionPerformed(evt);
            }
        });

        ViewDemo.setForeground(new java.awt.Color(0, 51, 153));
        ViewDemo.setText("ViewDemoGraphic");
        ViewDemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDemoActionPerformed(evt);
            }
        });

        viewaddress.setForeground(new java.awt.Color(0, 51, 153));
        viewaddress.setText("ViewAddress");
        viewaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewaddressActionPerformed(evt);
            }
        });

        ViewDriverLicense.setForeground(new java.awt.Color(0, 51, 153));
        ViewDriverLicense.setText("View Driver License");
        ViewDriverLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDriverLicenseActionPerformed(evt);
            }
        });

        ViewMedicalRecord.setForeground(new java.awt.Color(0, 51, 153));
        ViewMedicalRecord.setText("View Medical Record");
        ViewMedicalRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewMedicalRecordActionPerformed(evt);
            }
        });

        ViewAccountInfo.setForeground(new java.awt.Color(0, 51, 153));
        ViewAccountInfo.setText("View Account Info");
        ViewAccountInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAccountInfoActionPerformed(evt);
            }
        });

        ReportDetails.setForeground(new java.awt.Color(0, 51, 153));
        ReportDetails.setText("Report Details");
        ReportDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MedicalRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(DriverLicense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AccountInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewMedicalRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewDriverLicense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewAccountInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewaddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewDemo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Demographic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ReportDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Demographic, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AccountInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DriverLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MedicalRecord)
                .addGap(42, 42, 42)
                .addComponent(ViewDemo)
                .addGap(13, 13, 13)
                .addComponent(viewaddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewAccountInfo)
                .addGap(11, 11, 11)
                .addComponent(ViewDriverLicense)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewMedicalRecord)
                .addGap(45, 45, 45)
                .addComponent(ReportDetails)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jSplitPane.setLeftComponent(ControlPanel);

        javax.swing.GroupLayout WorkareaLayout = new javax.swing.GroupLayout(Workarea);
        Workarea.setLayout(WorkareaLayout);
        WorkareaLayout.setHorizontalGroup(
            WorkareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1309, Short.MAX_VALUE)
        );
        WorkareaLayout.setVerticalGroup(
            WorkareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        jSplitPane.setRightComponent(Workarea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressActionPerformed
        AddressPanel addpanel= new AddressPanel(address, fullreport);
        jSplitPane.setRightComponent(addpanel);
    }//GEN-LAST:event_AddressActionPerformed

    private void DemographicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemographicActionPerformed
        DemoPanel demopanel= new DemoPanel(product, fullreport);
        jSplitPane.setRightComponent(demopanel);
    }//GEN-LAST:event_DemographicActionPerformed

    private void AccountInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountInfoActionPerformed
       AccountInfoPanel accountpanel= new AccountInfoPanel(savings, checkin, fullreport);
       jSplitPane.setRightComponent(accountpanel);
    }//GEN-LAST:event_AccountInfoActionPerformed

    private void DriverLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DriverLicenseActionPerformed
        DriverPanel driverpanel = new DriverPanel(driver, fullreport);
        jSplitPane.setRightComponent(driverpanel);
    }//GEN-LAST:event_DriverLicenseActionPerformed

    private void MedicalRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicalRecordActionPerformed
        MedicalPanel medicalpanel=new MedicalPanel(medical, fullreport);
        jSplitPane.setRightComponent(medicalpanel);
    }//GEN-LAST:event_MedicalRecordActionPerformed

    private void ViewDemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDemoActionPerformed
        ViewDemoPanel viewdemopanel = new ViewDemoPanel(product, fullreport);
        jSplitPane.setRightComponent(viewdemopanel);
    }//GEN-LAST:event_ViewDemoActionPerformed

    private void viewaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewaddressActionPerformed
        ViewAddressPanel viewaddresspanel = new ViewAddressPanel(address, fullreport);
        jSplitPane.setRightComponent(viewaddresspanel);
    }//GEN-LAST:event_viewaddressActionPerformed

    private void ViewDriverLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDriverLicenseActionPerformed
        ViewDriverPanel viewdriverpanel = new ViewDriverPanel(driver, fullreport);
        jSplitPane.setRightComponent(viewdriverpanel);
    }//GEN-LAST:event_ViewDriverLicenseActionPerformed

    private void ViewMedicalRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewMedicalRecordActionPerformed
        ViewMedicalPanel viewmedicalpanel = new ViewMedicalPanel(medical, fullreport);
        jSplitPane.setRightComponent(viewmedicalpanel);
    }//GEN-LAST:event_ViewMedicalRecordActionPerformed

    private void ViewAccountInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAccountInfoActionPerformed
       ViewAccountInfo viewaccountinfo = new ViewAccountInfo(savings, checkin, fullreport);
       jSplitPane.setRightComponent(viewaccountinfo);
    }//GEN-LAST:event_ViewAccountInfoActionPerformed

    private void ReportDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportDetailsActionPerformed
        ViewReport viewreport = new ViewReport(fullreport, driver);
        jSplitPane.setRightComponent(viewreport);
    }//GEN-LAST:event_ReportDetailsActionPerformed

    /**
     * @param args the command line argument
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccountInfo;
    private javax.swing.JButton Address;
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JButton Demographic;
    private javax.swing.JButton DriverLicense;
    private javax.swing.JButton MedicalRecord;
    private javax.swing.JButton ReportDetails;
    private javax.swing.JButton ViewAccountInfo;
    private javax.swing.JButton ViewDemo;
    private javax.swing.JButton ViewDriverLicense;
    private javax.swing.JButton ViewMedicalRecord;
    private javax.swing.JPanel Workarea;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JButton viewaddress;
    // End of variables declaration//GEN-END:variables
}
