/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import javax.swing.JOptionPane;
import model.Fullreport;
import model.Medical;

/**
 *
 * @author Deepika Reddy
 */
public class MedicalPanel extends javax.swing.JPanel {
    Medical medical;
    Fullreport fullreport;
    public MedicalPanel(Medical medical, Fullreport fullreport) {
        initComponents();
        this.medical= medical;
        this.fullreport=fullreport;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        Medicalheading = new javax.swing.JLabel();
        medicalnum = new javax.swing.JLabel();
        txtmedicalnum = new javax.swing.JTextField();
        allergy1 = new javax.swing.JLabel();
        allergy2 = new javax.swing.JLabel();
        allergy3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtallergy1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtallergy2 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtallergy3 = new javax.swing.JTextArea();
        medicalsave = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        jButton1.setText("jButton1");

        Medicalheading.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Medicalheading.setForeground(new java.awt.Color(0, 51, 153));
        Medicalheading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Medicalheading.setText("Medical Record");

        medicalnum.setForeground(new java.awt.Color(0, 51, 153));
        medicalnum.setText("Medical Record Number:");

        txtmedicalnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmedicalnumActionPerformed(evt);
            }
        });

        allergy1.setForeground(new java.awt.Color(0, 51, 153));
        allergy1.setText("Allergy1:");

        allergy2.setForeground(new java.awt.Color(0, 51, 153));
        allergy2.setText("Allergy2:");

        allergy3.setForeground(new java.awt.Color(0, 51, 153));
        allergy3.setText("Allergy3:");

        txtallergy1.setColumns(20);
        txtallergy1.setRows(5);
        jScrollPane2.setViewportView(txtallergy1);

        txtallergy2.setColumns(20);
        txtallergy2.setRows(5);
        jScrollPane3.setViewportView(txtallergy2);

        txtallergy3.setColumns(20);
        txtallergy3.setRows(5);
        jScrollPane5.setViewportView(txtallergy3);

        medicalsave.setForeground(new java.awt.Color(0, 51, 153));
        medicalsave.setText("Save");
        medicalsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(medicalnum, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(allergy1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(allergy2)
                                    .addComponent(allergy3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmedicalnum)))
                            .addComponent(Medicalheading, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(medicalsave)))
                .addContainerGap(354, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Medicalheading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicalnum)
                    .addComponent(txtmedicalnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allergy1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allergy2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allergy3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(medicalsave))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtmedicalnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmedicalnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmedicalnumActionPerformed

    private void medicalsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalsaveActionPerformed
      medical.setMedicalnum(txtmedicalnum.getText());
      medical.setAllergy1(txtallergy1.getText());
      medical.setAllergy2(txtallergy2.getText());
      medical.setAllergy3(txtallergy3.getText());
      
      fullreport.setMedical(medical);
       JOptionPane.showMessageDialog(this,"Medical Details Entered");
    }//GEN-LAST:event_medicalsaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Medicalheading;
    private javax.swing.JLabel allergy1;
    private javax.swing.JLabel allergy2;
    private javax.swing.JLabel allergy3;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JLabel medicalnum;
    private javax.swing.JButton medicalsave;
    private javax.swing.JTextArea txtallergy1;
    private javax.swing.JTextArea txtallergy2;
    private javax.swing.JTextArea txtallergy3;
    private javax.swing.JTextField txtmedicalnum;
    // End of variables declaration//GEN-END:variables
}
