/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import model.Driver;
import model.Fullreport;


public class ViewDriverPanel extends javax.swing.JPanel {

    
    
    Driver driver;
    Fullreport fullreport;
    public ViewDriverPanel(Driver driver, Fullreport fullreport) {
        initComponents();
        this.driver=driver;
        this.fullreport=fullreport;
        displayDriver();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateofexpiration_ = new javax.swing.JLabel();
        bloodtype_ = new javax.swing.JLabel();
        picture_ = new javax.swing.JLabel();
        txtlicense_ = new javax.swing.JTextField();
        txtdateofissue_ = new javax.swing.JTextField();
        txtdateofexpiration_ = new javax.swing.JTextField();
        txtbloodtype_ = new javax.swing.JTextField();
        driverheading = new javax.swing.JLabel();
        licensenumber_ = new javax.swing.JLabel();
        dateofissue_ = new javax.swing.JLabel();
        picturelabel = new javax.swing.JLabel();

        dateofexpiration_.setForeground(new java.awt.Color(0, 51, 153));
        dateofexpiration_.setText("Date of Expiration:");

        bloodtype_.setForeground(new java.awt.Color(0, 51, 153));
        bloodtype_.setText("Blood Type:");

        picture_.setForeground(new java.awt.Color(0, 51, 153));
        picture_.setText("Picture:");

        txtlicense_.setEditable(false);
        txtlicense_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlicense_ActionPerformed(evt);
            }
        });

        txtdateofissue_.setEditable(false);

        txtdateofexpiration_.setEditable(false);

        txtbloodtype_.setEditable(false);

        driverheading.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        driverheading.setForeground(new java.awt.Color(0, 51, 153));
        driverheading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        driverheading.setText("Driver License Details");

        licensenumber_.setForeground(new java.awt.Color(0, 51, 153));
        licensenumber_.setText("License Number:");

        dateofissue_.setForeground(new java.awt.Color(0, 51, 153));
        dateofissue_.setText("Date of Issue:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(driverheading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(licensenumber_)
                    .addComponent(dateofissue_)
                    .addComponent(dateofexpiration_)
                    .addComponent(bloodtype_)
                    .addComponent(picture_))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtlicense_)
                    .addComponent(txtdateofissue_)
                    .addComponent(txtdateofexpiration_)
                    .addComponent(txtbloodtype_, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(picturelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(driverheading)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(licensenumber_)
                    .addComponent(txtlicense_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateofissue_)
                    .addComponent(txtdateofissue_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateofexpiration_)
                    .addComponent(txtdateofexpiration_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodtype_)
                    .addComponent(txtbloodtype_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(picture_))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(picturelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtlicense_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlicense_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlicense_ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bloodtype_;
    private javax.swing.JLabel dateofexpiration_;
    private javax.swing.JLabel dateofissue_;
    private javax.swing.JLabel driverheading;
    private javax.swing.JLabel licensenumber_;
    private javax.swing.JLabel picture_;
    private javax.swing.JLabel picturelabel;
    private javax.swing.JTextField txtbloodtype_;
    private javax.swing.JTextField txtdateofexpiration_;
    private javax.swing.JTextField txtdateofissue_;
    private javax.swing.JTextField txtlicense_;
    // End of variables declaration//GEN-END:variables

    private void displayDriver() {
        txtlicense_.setText(driver.getLicense());
        txtdateofissue_.setText(driver.getDateofissue());
        txtdateofexpiration_.setText(driver.getDateofexpiration());
        txtbloodtype_.setText(driver.getBloodtype());
        
              Image pic = driver.getPicture();
        ImageIcon Imicon = new ImageIcon(pic);
        picturelabel.setIcon(Imicon); 
       
    }
}
