/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.AccountInfo;
import model.Fullreport;


public class ViewAccountInfo extends javax.swing.JPanel {
  AccountInfo savings;
  AccountInfo checkin;
  Fullreport fullreport;
    public ViewAccountInfo(AccountInfo savings, AccountInfo checkin, Fullreport fullreport) {
        initComponents();
        this.savings=savings;
        this.checkin=checkin;
        this.fullreport=fullreport;
        displayAccountInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accounttype1 = new javax.swing.JLabel();
        txtaccounttype1_ = new javax.swing.JLabel();
        accountbalance1 = new javax.swing.JLabel();
        accounttype_ = new javax.swing.JLabel();
        txtbankname_ = new javax.swing.JTextField();
        txtbankname1_ = new javax.swing.JTextField();
        txtroutingnumber_ = new javax.swing.JTextField();
        txtroutingnumber1_ = new javax.swing.JTextField();
        txtaccountnumber_ = new javax.swing.JTextField();
        txtaccountnumber1_ = new javax.swing.JTextField();
        txtaccountbalance_ = new javax.swing.JTextField();
        txtaccountbalance1_ = new javax.swing.JTextField();
        txtaccounttype_ = new javax.swing.JTextField();
        bankheading = new javax.swing.JLabel();
        bankheading1 = new javax.swing.JLabel();
        bankname_ = new javax.swing.JLabel();
        bankname1 = new javax.swing.JLabel();
        routingnumber_ = new javax.swing.JLabel();
        routingnumber1 = new javax.swing.JLabel();
        accountnumber_ = new javax.swing.JLabel();
        accountnumber1 = new javax.swing.JLabel();
        accountbalance_ = new javax.swing.JLabel();
        txtaccounttype1 = new javax.swing.JTextField();

        accounttype1.setForeground(new java.awt.Color(0, 51, 153));
        accounttype1.setText("Account Type:");

        accountbalance1.setForeground(new java.awt.Color(0, 51, 153));
        accountbalance1.setText("Account Balance:");

        accounttype_.setForeground(new java.awt.Color(0, 51, 153));
        accounttype_.setText("Account Type:");

        txtbankname_.setEditable(false);

        txtbankname1_.setEditable(false);
        txtbankname1_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbankname1_ActionPerformed(evt);
            }
        });

        txtroutingnumber_.setEditable(false);

        txtroutingnumber1_.setEditable(false);
        txtroutingnumber1_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtroutingnumber1_ActionPerformed(evt);
            }
        });

        txtaccountnumber_.setEditable(false);

        txtaccountnumber1_.setEditable(false);
        txtaccountnumber1_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaccountnumber1_ActionPerformed(evt);
            }
        });

        txtaccountbalance_.setEditable(false);

        txtaccountbalance1_.setEditable(false);

        txtaccounttype_.setEditable(false);
        txtaccounttype_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaccounttype_ActionPerformed(evt);
            }
        });

        bankheading.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bankheading.setForeground(new java.awt.Color(0, 51, 153));
        bankheading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bankheading.setText("Savings Bank Details");

        bankheading1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bankheading1.setForeground(new java.awt.Color(0, 51, 153));
        bankheading1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bankheading1.setText("Checkin Bank Details");

        bankname_.setForeground(new java.awt.Color(0, 51, 153));
        bankname_.setText("Bank Name:");

        bankname1.setForeground(new java.awt.Color(0, 51, 153));
        bankname1.setText("Bank Name:");

        routingnumber_.setForeground(new java.awt.Color(0, 51, 153));
        routingnumber_.setText("Routing Number:");

        routingnumber1.setForeground(new java.awt.Color(0, 51, 153));
        routingnumber1.setText("Routing Number:");

        accountnumber_.setForeground(new java.awt.Color(0, 51, 153));
        accountnumber_.setText("Account Number");

        accountnumber1.setForeground(new java.awt.Color(0, 51, 153));
        accountnumber1.setText("Account Number");

        accountbalance_.setForeground(new java.awt.Color(0, 51, 153));
        accountbalance_.setText("Account Balance:");

        txtaccounttype1.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(352, Short.MAX_VALUE)
                .addComponent(txtaccounttype1_, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(accounttype1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(txtaccounttype1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(bankheading, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bankheading1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(accountnumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtaccountnumber1_, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(accountbalance_, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                        .addComponent(accountnumber_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(routingnumber_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bankname_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(accounttype_, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bankname1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(routingnumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtroutingnumber_, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                        .addComponent(txtaccountnumber_)
                                        .addComponent(txtaccountbalance_)
                                        .addComponent(txtbankname_)
                                        .addComponent(txtaccounttype_))
                                    .addComponent(txtbankname1_, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtroutingnumber1_, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(accountbalance1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtaccountbalance1_, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(176, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(337, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtaccounttype1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accounttype1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(txtaccounttype1_, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(bankheading, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtbankname_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtroutingnumber_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bankname_, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(routingnumber_, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(accountnumber_)
                        .addComponent(txtaccountnumber_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtaccountbalance_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(accountbalance_, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(6, 6, 6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtaccounttype_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(accounttype_, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(bankheading1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bankname1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtbankname1_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(routingnumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtroutingnumber1_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(accountnumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtaccountnumber1_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(accountbalance1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtaccountbalance1_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(127, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtbankname1_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbankname1_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbankname1_ActionPerformed

    private void txtroutingnumber1_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtroutingnumber1_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtroutingnumber1_ActionPerformed

    private void txtaccountnumber1_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaccountnumber1_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaccountnumber1_ActionPerformed

    private void txtaccounttype_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaccounttype_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaccounttype_ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountbalance1;
    private javax.swing.JLabel accountbalance_;
    private javax.swing.JLabel accountnumber1;
    private javax.swing.JLabel accountnumber_;
    private javax.swing.JLabel accounttype1;
    private javax.swing.JLabel accounttype_;
    private javax.swing.JLabel bankheading;
    private javax.swing.JLabel bankheading1;
    private javax.swing.JLabel bankname1;
    private javax.swing.JLabel bankname_;
    private javax.swing.JLabel routingnumber1;
    private javax.swing.JLabel routingnumber_;
    private javax.swing.JTextField txtaccountbalance1_;
    private javax.swing.JTextField txtaccountbalance_;
    private javax.swing.JTextField txtaccountnumber1_;
    private javax.swing.JTextField txtaccountnumber_;
    private javax.swing.JTextField txtaccounttype1;
    private javax.swing.JLabel txtaccounttype1_;
    private javax.swing.JTextField txtaccounttype_;
    private javax.swing.JTextField txtbankname1_;
    private javax.swing.JTextField txtbankname_;
    private javax.swing.JTextField txtroutingnumber1_;
    private javax.swing.JTextField txtroutingnumber_;
    // End of variables declaration//GEN-END:variables

    private void displayAccountInfo() {
        txtbankname_.setText(savings.getBankname());
        txtroutingnumber_.setText(savings.getRoutingnumber());
        txtaccountnumber_.setText(savings.getAccontnumber());
        txtaccountbalance_.setText(savings.getAccountbalance());
        txtaccounttype_.setText(savings.getAccounttype());
        
        txtbankname1_.setText(checkin.getBankname());
        txtroutingnumber1_.setText(checkin.getRoutingnumber());
        txtaccountnumber1_.setText(checkin.getAccontnumber());
        txtaccountbalance1_.setText(checkin.getAccountbalance());
        txtaccounttype1_.setText(checkin.getAccounttype());
        
    }
}
