/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;


import java.awt.Image;
import javax.swing.ImageIcon;
import model.Driver;
import model.Fullreport;

/**
 *
 * @author Deepika Reddy
 */
public class ViewReport extends javax.swing.JPanel {

    Driver driver;
    Fullreport fullreport;
    public ViewReport(Fullreport fullreport, Driver driver) {
        initComponents();
        this.fullreport=fullreport;
        this.driver=driver;
        displayFullreport();
    }
    
    private void displayFullreport() 
    {
      
        txtfirstname.setText(fullreport.getProduct().getFirstname());
        txtlastname.setText(fullreport.getProduct().getLastname());
        txtphonenumber.setText(fullreport.getProduct().getPhonenumber());
        txtdateofbirth.setText(fullreport.getProduct().getDateofbirth());
        txtage.setText(fullreport.getProduct().getAge());
        txtweight.setText(fullreport.getProduct().getWeight());
        txtheight.setText(fullreport.getProduct().getHeight());
        txtssn.setText(fullreport.getProduct().getSsn());
        
        txtstreet.setText(fullreport.getAddress().getStreet());
        txtcity.setText(fullreport.getAddress().getCity());
        txtstate.setText(fullreport.getAddress().getState());
        txtzipcode.setText(fullreport.getAddress().getZipcode());
        
        txtbankname.setText(fullreport.getSavings().getBankname());
        txtroutingnumber.setText(fullreport.getSavings().getRoutingnumber());
        txtaccountnumber.setText(fullreport.getSavings().getAccontnumber());
        txtaccountbalance.setText(fullreport.getSavings().getAccountbalance());
        txtaccounttype.setText(fullreport.getSavings().getAccounttype());
        
        txtbankname1.setText(fullreport.getCheckin().getBankname());
        txtroutingnumber1.setText(fullreport.getCheckin().getRoutingnumber());
        txtaccountnumber1.setText(fullreport.getCheckin().getAccontnumber());
        txtaccountbalance1.setText(fullreport.getCheckin().getAccountbalance());
        txtaccounttype1.setText(fullreport.getCheckin().getAccounttype());
        
        txtmedical.setText(fullreport.getMedical().getMedicalnum());
        txtallergy1.setText(fullreport.getMedical().getAllergy1());
        txtallergy2.setText(fullreport.getMedical().getAllergy2());
        txtallergy3.setText(fullreport.getMedical().getAllergy3());
        
        txtdriverlicense.setText(fullreport.getDriver().getLicense());
        txtdateofissue.setText(fullreport.getDriver().getDateofissue());
        txtdateofexpiration.setText(fullreport.getDriver().getDateofexpiration());
        txtbloodtype.setText(fullreport.getDriver().getBloodtype());
        
        
          Image pic = driver.getPicture();
        ImageIcon Imicon = new ImageIcon(pic);
        picturelabel.setIcon(Imicon); 
       
        
           
        
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstname = new javax.swing.JLabel();
        lastname = new javax.swing.JLabel();
        phonenumber = new javax.swing.JLabel();
        dateofbirth = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        weight = new javax.swing.JLabel();
        ssn = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JTextField();
        txtlastname = new javax.swing.JTextField();
        txtphonenumber = new javax.swing.JTextField();
        txtdateofbirth = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtheight = new javax.swing.JTextField();
        txtweight = new javax.swing.JTextField();
        txtssn = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        street = new javax.swing.JLabel();
        txtstreet = new javax.swing.JTextField();
        city = new javax.swing.JLabel();
        txtcity = new javax.swing.JTextField();
        state = new javax.swing.JLabel();
        txtstate = new javax.swing.JTextField();
        Zipcode = new javax.swing.JLabel();
        txtzipcode = new javax.swing.JTextField();
        bankname = new javax.swing.JLabel();
        txtbankname = new javax.swing.JTextField();
        routingnumber = new javax.swing.JLabel();
        txtaccounttype = new javax.swing.JTextField();
        accountnumber = new javax.swing.JLabel();
        txtroutingnumber = new javax.swing.JTextField();
        accountbalance = new javax.swing.JLabel();
        txtaccountnumber = new javax.swing.JTextField();
        accounttype = new javax.swing.JLabel();
        txtaccountbalance1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtbankname1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtroutingnumber1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtaccountnumber1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtaccountbalance = new javax.swing.JTextField();
        txtaccounttype1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtmedical = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtallergy1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtallergy2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtallergy3 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtdriverlicense = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtdateofissue = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtdateofexpiration = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtbloodtype = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        picturelabel = new javax.swing.JLabel();

        setForeground(new java.awt.Color(102, 102, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PERSONAL INFORMATION");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 976, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Demographic");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 17, 101, -1));

        firstname.setForeground(new java.awt.Color(0, 51, 153));
        firstname.setText("First Name:");
        add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 41, 67, -1));

        lastname.setForeground(new java.awt.Color(0, 51, 153));
        lastname.setText("LastName:");
        add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        phonenumber.setForeground(new java.awt.Color(0, 51, 153));
        phonenumber.setText("Phone Number:");
        add(phonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        dateofbirth.setForeground(new java.awt.Color(0, 51, 153));
        dateofbirth.setText("Date of Birth:");
        add(dateofbirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        age.setForeground(new java.awt.Color(0, 51, 153));
        age.setText("Age:");
        add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        weight.setForeground(new java.awt.Color(0, 51, 153));
        weight.setText("Weight:");
        add(weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        ssn.setForeground(new java.awt.Color(0, 51, 153));
        ssn.setText("Social Security Number:");
        add(ssn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        txtfirstname.setEditable(false);
        txtfirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfirstnameActionPerformed(evt);
            }
        });
        add(txtfirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 38, 88, -1));

        txtlastname.setEditable(false);
        txtlastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlastnameActionPerformed(evt);
            }
        });
        add(txtlastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 69, 88, -1));

        txtphonenumber.setEditable(false);
        add(txtphonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 95, 88, -1));

        txtdateofbirth.setEditable(false);
        txtdateofbirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateofbirthActionPerformed(evt);
            }
        });
        add(txtdateofbirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 88, 20));

        txtage.setEditable(false);
        txtage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtageActionPerformed(evt);
            }
        });
        add(txtage, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 88, -1));

        txtheight.setEditable(false);
        txtheight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtheightActionPerformed(evt);
            }
        });
        add(txtheight, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 88, -1));

        txtweight.setEditable(false);
        txtweight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtweightActionPerformed(evt);
            }
        });
        add(txtweight, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 88, 20));

        txtssn.setEditable(false);
        add(txtssn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 88, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 153));
        jLabel11.setText("Address");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 115, -1));

        street.setForeground(new java.awt.Color(0, 51, 153));
        street.setText("Street Address:");
        add(street, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 357, -1, -1));

        txtstreet.setEditable(false);
        add(txtstreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 363, 82, 38));

        city.setForeground(new java.awt.Color(0, 51, 153));
        city.setText("City:");
        add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 415, -1, -1));

        txtcity.setEditable(false);
        add(txtcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 412, 82, -1));

        state.setForeground(new java.awt.Color(0, 51, 153));
        state.setText("State:");
        add(state, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 446, -1, -1));

        txtstate.setEditable(false);
        add(txtstate, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 443, 82, -1));

        Zipcode.setForeground(new java.awt.Color(0, 51, 153));
        Zipcode.setText("Zipcode:");
        add(Zipcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        txtzipcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtzipcodeActionPerformed(evt);
            }
        });
        add(txtzipcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 82, -1));

        bankname.setForeground(new java.awt.Color(0, 51, 153));
        bankname.setText("Bank Name:");
        add(bankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        txtbankname.setEditable(false);
        txtbankname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbanknameActionPerformed(evt);
            }
        });
        add(txtbankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 89, -1));

        routingnumber.setForeground(new java.awt.Color(0, 51, 153));
        routingnumber.setText("RoutingNumber:");
        add(routingnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        txtaccounttype.setEditable(false);
        txtaccounttype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaccounttypeActionPerformed(evt);
            }
        });
        add(txtaccounttype, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 89, -1));

        accountnumber.setForeground(new java.awt.Color(0, 51, 153));
        accountnumber.setText("Account Number:");
        add(accountnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        txtroutingnumber.setEditable(false);
        txtroutingnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtroutingnumberActionPerformed(evt);
            }
        });
        add(txtroutingnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 89, -1));

        accountbalance.setForeground(new java.awt.Color(0, 51, 153));
        accountbalance.setText("Account Balance:");
        add(accountbalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, 24));

        txtaccountnumber.setEditable(false);
        txtaccountnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaccountnumberActionPerformed(evt);
            }
        });
        add(txtaccountnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 89, -1));

        accounttype.setForeground(new java.awt.Color(0, 51, 153));
        accounttype.setText("Account Type:");
        add(accounttype, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        txtaccountbalance1.setEditable(false);
        txtaccountbalance1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaccountbalance1ActionPerformed(evt);
            }
        });
        add(txtaccountbalance1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 130, 94, -1));

        jLabel18.setForeground(new java.awt.Color(0, 51, 153));
        jLabel18.setText("Bank Name:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, -1, -1));

        txtbankname1.setEditable(false);
        txtbankname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbankname1ActionPerformed(evt);
            }
        });
        add(txtbankname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, 94, -1));

        jLabel19.setForeground(new java.awt.Color(0, 51, 153));
        jLabel19.setText("RoutingNumber:");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, -1, -1));

        txtroutingnumber1.setEditable(false);
        txtroutingnumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtroutingnumber1ActionPerformed(evt);
            }
        });
        add(txtroutingnumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, 94, -1));

        jLabel20.setForeground(new java.awt.Color(0, 51, 153));
        jLabel20.setText("Account Number:");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, -1, -1));

        txtaccountnumber1.setEditable(false);
        txtaccountnumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaccountnumber1ActionPerformed(evt);
            }
        });
        add(txtaccountnumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 100, 94, -1));

        jLabel21.setForeground(new java.awt.Color(0, 51, 153));
        jLabel21.setText("Account Balance:");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, -1, 20));

        txtaccountbalance.setEditable(false);
        txtaccountbalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaccountbalanceActionPerformed(evt);
            }
        });
        add(txtaccountbalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 89, -1));

        txtaccounttype1.setEditable(false);
        txtaccounttype1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaccounttype1ActionPerformed(evt);
            }
        });
        add(txtaccounttype1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, 94, -1));

        jLabel22.setForeground(new java.awt.Color(0, 51, 153));
        jLabel22.setText("Account Type:");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 51, 153));
        jLabel23.setText("Medical Information");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 140, -1));

        jLabel24.setForeground(new java.awt.Color(0, 51, 153));
        jLabel24.setText("Medical Record Number:");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, -1));

        txtmedical.setEditable(false);
        txtmedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmedicalActionPerformed(evt);
            }
        });
        add(txtmedical, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 90, -1));

        jLabel25.setForeground(new java.awt.Color(0, 51, 153));
        jLabel25.setText("Allergy1:");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, -1, -1));

        txtallergy1.setEditable(false);
        txtallergy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtallergy1ActionPerformed(evt);
            }
        });
        add(txtallergy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 87, -1));

        jLabel26.setForeground(new java.awt.Color(0, 51, 153));
        jLabel26.setText("Allergy2:");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, -1, -1));

        txtallergy2.setEditable(false);
        add(txtallergy2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 87, -1));

        jLabel27.setForeground(new java.awt.Color(0, 51, 153));
        jLabel27.setText("Allergy3:");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, -1, -1));

        txtallergy3.setEditable(false);
        txtallergy3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtallergy3ActionPerformed(evt);
            }
        });
        add(txtallergy3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 87, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 51, 153));
        jLabel28.setText("Driver License");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, -1, -1));

        jLabel29.setForeground(new java.awt.Color(0, 51, 153));
        jLabel29.setText("Driver License:");
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, 84, -1));

        txtdriverlicense.setEditable(false);
        txtdriverlicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdriverlicenseActionPerformed(evt);
            }
        });
        add(txtdriverlicense, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 370, 80, -1));

        jLabel30.setForeground(new java.awt.Color(0, 51, 153));
        jLabel30.setText("Date of Issue:");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, -1, -1));

        txtdateofissue.setEditable(false);
        txtdateofissue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateofissueActionPerformed(evt);
            }
        });
        add(txtdateofissue, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, 80, -1));

        jLabel31.setForeground(new java.awt.Color(0, 51, 153));
        jLabel31.setText("Date of Expiration:");
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 430, -1, -1));

        txtdateofexpiration.setEditable(false);
        txtdateofexpiration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateofexpirationActionPerformed(evt);
            }
        });
        add(txtdateofexpiration, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 430, 77, -1));

        jLabel32.setForeground(new java.awt.Color(0, 51, 153));
        jLabel32.setText("BloodType:");
        add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, -1, -1));

        txtbloodtype.setEditable(false);
        txtbloodtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbloodtypeActionPerformed(evt);
            }
        });
        add(txtbloodtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 470, 77, -1));

        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("Height:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 56, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("Savings Account");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 17, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setText("Checkin Account");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(769, 17, -1, -1));

        picturelabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(picturelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 30, 150, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void txtlastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastnameActionPerformed

    private void txtheightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtheightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtheightActionPerformed

    private void txtageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtageActionPerformed

    private void txtaccounttypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaccounttypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaccounttypeActionPerformed

    private void txtaccountnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaccountnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaccountnumberActionPerformed

    private void txtaccountbalance1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaccountbalance1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaccountbalance1ActionPerformed

    private void txtaccountbalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaccountbalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaccountbalanceActionPerformed

    private void txtaccounttype1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaccounttype1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaccounttype1ActionPerformed

    private void txtdateofbirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateofbirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateofbirthActionPerformed

    private void txtallergy3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtallergy3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtallergy3ActionPerformed

    private void txtbanknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbanknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbanknameActionPerformed

    private void txtroutingnumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtroutingnumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtroutingnumber1ActionPerformed

    private void txtaccountnumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaccountnumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaccountnumber1ActionPerformed

    private void txtfirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstnameActionPerformed

    private void txtweightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtweightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtweightActionPerformed

    private void txtroutingnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtroutingnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtroutingnumberActionPerformed

    private void txtbankname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbankname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbankname1ActionPerformed

    private void txtmedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmedicalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmedicalActionPerformed

    private void txtzipcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtzipcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtzipcodeActionPerformed

    private void txtdateofissueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateofissueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateofissueActionPerformed

    private void txtdateofexpirationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateofexpirationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateofexpirationActionPerformed

    private void txtbloodtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbloodtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbloodtypeActionPerformed

    private void txtallergy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtallergy1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtallergy1ActionPerformed

    private void txtdriverlicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdriverlicenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdriverlicenseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Zipcode;
    private javax.swing.JLabel accountbalance;
    private javax.swing.JLabel accountnumber;
    private javax.swing.JLabel accounttype;
    private javax.swing.JLabel age;
    private javax.swing.JLabel bankname;
    private javax.swing.JLabel city;
    private javax.swing.JLabel dateofbirth;
    private javax.swing.JLabel firstname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lastname;
    private javax.swing.JLabel phonenumber;
    private javax.swing.JLabel picturelabel;
    private javax.swing.JLabel routingnumber;
    private javax.swing.JLabel ssn;
    private javax.swing.JLabel state;
    private javax.swing.JLabel street;
    private javax.swing.JTextField txtaccountbalance;
    private javax.swing.JTextField txtaccountbalance1;
    private javax.swing.JTextField txtaccountnumber;
    private javax.swing.JTextField txtaccountnumber1;
    private javax.swing.JTextField txtaccounttype;
    private javax.swing.JTextField txtaccounttype1;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtallergy1;
    private javax.swing.JTextField txtallergy2;
    private javax.swing.JTextField txtallergy3;
    private javax.swing.JTextField txtbankname;
    private javax.swing.JTextField txtbankname1;
    private javax.swing.JTextField txtbloodtype;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtdateofbirth;
    private javax.swing.JTextField txtdateofexpiration;
    private javax.swing.JTextField txtdateofissue;
    private javax.swing.JTextField txtdriverlicense;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtheight;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtmedical;
    private javax.swing.JTextField txtphonenumber;
    private javax.swing.JTextField txtroutingnumber;
    private javax.swing.JTextField txtroutingnumber1;
    private javax.swing.JTextField txtssn;
    private javax.swing.JTextField txtstate;
    private javax.swing.JTextField txtstreet;
    private javax.swing.JTextField txtweight;
    private javax.swing.JTextField txtzipcode;
    private javax.swing.JLabel weight;
    // End of variables declaration//GEN-END:variables

    

    
}
