/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Fullreport;
import model.Medical;

/**
 *
 * @author Deepika Reddy
 */
public class ViewMedicalPanel extends javax.swing.JPanel {

    Medical medical;
    Fullreport fullreport;
    
    public ViewMedicalPanel(Medical medical, Fullreport fullreport) {
        initComponents();
        this.medical=medical;
        this.fullreport=fullreport;
        displayMedical();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        allergy3_ = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtallergy3_ = new javax.swing.JTextArea();
        Medicalheading = new javax.swing.JLabel();
        medicalnum_ = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtallergy1_ = new javax.swing.JTextArea();
        txtmedicalnum_ = new javax.swing.JTextField();
        allergy1_ = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtallergy2_ = new javax.swing.JTextArea();
        allergy2_ = new javax.swing.JLabel();

        allergy3_.setForeground(new java.awt.Color(0, 51, 153));
        allergy3_.setText("Allergy3:");

        txtallergy3_.setEditable(false);
        txtallergy3_.setColumns(20);
        txtallergy3_.setRows(5);
        jScrollPane5.setViewportView(txtallergy3_);

        Medicalheading.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Medicalheading.setForeground(new java.awt.Color(0, 51, 153));
        Medicalheading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Medicalheading.setText("Medical Record");

        medicalnum_.setForeground(new java.awt.Color(0, 51, 153));
        medicalnum_.setText("Medical Record Number:");

        txtallergy1_.setEditable(false);
        txtallergy1_.setColumns(20);
        txtallergy1_.setRows(5);
        jScrollPane2.setViewportView(txtallergy1_);

        txtmedicalnum_.setEditable(false);
        txtmedicalnum_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmedicalnum_ActionPerformed(evt);
            }
        });

        allergy1_.setForeground(new java.awt.Color(0, 51, 153));
        allergy1_.setText("Allergy1:");

        txtallergy2_.setColumns(20);
        txtallergy2_.setRows(5);
        jScrollPane3.setViewportView(txtallergy2_);

        allergy2_.setForeground(new java.awt.Color(0, 51, 153));
        allergy2_.setText("Allergy2:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(medicalnum_, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(allergy1_, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(allergy2_)
                            .addComponent(allergy3_, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmedicalnum_)))
                    .addComponent(Medicalheading, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Medicalheading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicalnum_)
                    .addComponent(txtmedicalnum_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allergy1_))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allergy2_, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allergy3_))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtmedicalnum_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmedicalnum_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmedicalnum_ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Medicalheading;
    private javax.swing.JLabel allergy1_;
    private javax.swing.JLabel allergy2_;
    private javax.swing.JLabel allergy3_;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel medicalnum_;
    private javax.swing.JTextArea txtallergy1_;
    private javax.swing.JTextArea txtallergy2_;
    private javax.swing.JTextArea txtallergy3_;
    private javax.swing.JTextField txtmedicalnum_;
    // End of variables declaration//GEN-END:variables

    private void displayMedical() {
        txtmedicalnum_.setText(medical.getMedicalnum());
        txtallergy1_.setText(medical.getAllergy1());
        txtallergy2_.setText(medical.getAllergy2());
        txtallergy3_.setText(medical.getAllergy3());
        
    }
}
